### PR TITLE
WIP redesign

### PR DESCRIPTION
**Pull request by Michal-Szczepaniak**
Your files structure is totally wrecked. Didn't bother to fix c++, fixed qml instead. All old files are in Old directory to assist redesigning. All New files are placed correctly. Currently working pages: settings and editing server dialog. Adding server is now in pulldown menu. Clicking on server causes connect. Switched to tab layout (it fits so god damn well)

### CODE REVIEW

**Comment by Julien-Blanc-tgcm** [comment]
Please don't break the file structure. This makes it just impossible to track any differences, and will make any rebase attempt real pita. This is also very likely to break translations.  There is also no need to keep old files in a separate old directory, git is designed for this. 

As for the changes themselves :
* a tabbed view does not *fits so god damn well*. It feels alien (especially the way you did it, no jolla delivered sailfish app does this). It puts settings (a thing you only do usually once) at the same ui level as other items, which is a bad thing (i know the current ui has the same issue, but i thought all this was about improving it).
* some files contains some copyright headers that mentions they’re part of musikilo : they should not be present.

**Comment by Michal-Szczepaniak** [comment]
"Please don't break the file structure"
I think that current file structure needs improvements. Git can track renamed files, but since I'm doing mostly a rewrite with some components recycled, it could be a good point to fix the naming.

"This makes it just impossible to track any differences"
There are no differences, it's complete rewrite and just some components recycled

"There is also no need to keep old files in a separate old directory, git is designed for this."
This PR is still WIP, I will fix it later on

"And will make any rebase attempt real pita"
look above. We need to  get past it

"A tabbed view does not fit so god-damn well. It feels alien (especially the way you did it, no jolla delivered sailfish app does this)."
What jolla did with tab layout is completely wrong. Sfos users are well-used to this layout because of piepmatz and couple other apps. It gives you possibility to jump from for example selecting music to playback/remote control.

"It puts settings (a thing you only usually do once) at the same UI level as other items, which is a bad thing"
not really. You put connecting to servers in pull-down menu which can cause 100 pull-down menu entries which is very wrong. I made it so that click on settings entry connects to server so settings are part of usability.

"Some files contains some copyright headers that mentions they’re part of musikilo : they should not be present"
again it's **work in progress**

**Comment by comradekingu** [comment]
@Michal-Szczepaniak Is this both a graphics and internal file-structure change? Does it have to be both?
If you put the old files in their own branch everyone gets along?
What is piepmatz? (I am a Jolla user and I don't know).

I would expect "settings" to be the pulldown and the various servers to be the scrolling screen field if there are many. (Like connecting to Wi-Fi".) I suppose it is OK if there are just a few and switching between them often is part of the workflow.

Can I see a screenshot or understand how it works somehow?

Can it be done in one file-structure PR and one for graphics?

**Comment by Michal-Szczepaniak** [comment]
I'll just roll my fork

**Comment by Julien-Blanc-tgcm** [comment]
@Michal-Szczepaniak Do as you wish, this is what open source is for. However, you raised valid issues about the interface, most of which should be addressed by now. You should at least give the new version a try. We have a disagreement about tabs (i really don't like how there is no gesture navigation in Musikilo, for example), but for others area every improvement is welcomed, be it suggestions or code.

As for the file structure, i agree it is far from being perfect (kontroller has a long history predating its publication, which partly explain the mess, the remaining explanation is me having be a bit lazy about that part). However, i tend to prefer improving things by small steps, which reduce the risks of regressions, rather than large changes which are difficult to evaluate.

**Comment by Michal-Szczepaniak** [comment]
If you don't want the tabs layout (which i'm against too) I will think about it, if i get something i will make new, cleaner pr. This pr was made because you or someone wanted me to just create it even if its unfinished and work on it later.

**Comment by Michal-Szczepaniak** [comment]
We've got quite a nice idea that you should like

**Pull request closed without merging**
